/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as PropagationRouteImport } from './routes/propagation'
import { Route as OntologyRouteImport } from './routes/ontology'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as GraphsRouteImport } from './routes/graphs'
import { Route as FaultsRouteImport } from './routes/faults'
import { Route as IndexRouteImport } from './routes/index'

const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const PropagationRoute = PropagationRouteImport.update({
  id: '/propagation',
  path: '/propagation',
  getParentRoute: () => rootRouteImport,
} as any)
const OntologyRoute = OntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsRoute = GraphsRouteImport.update({
  id: '/graphs',
  path: '/graphs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaultsRoute = FaultsRouteImport.update({
  id: '/faults',
  path: '/faults',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faults': typeof FaultsRoute
  '/graphs': typeof GraphsRoute
  '/logs': typeof LogsRoute
  '/ontology': typeof OntologyRoute
  '/propagation': typeof PropagationRoute
  '/telemetry': typeof TelemetryRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faults': typeof FaultsRoute
  '/graphs': typeof GraphsRoute
  '/logs': typeof LogsRoute
  '/ontology': typeof OntologyRoute
  '/propagation': typeof PropagationRoute
  '/telemetry': typeof TelemetryRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faults': typeof FaultsRoute
  '/graphs': typeof GraphsRoute
  '/logs': typeof LogsRoute
  '/ontology': typeof OntologyRoute
  '/propagation': typeof PropagationRoute
  '/telemetry': typeof TelemetryRoute
  '/twin': typeof TwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faults'
    | '/graphs'
    | '/logs'
    | '/ontology'
    | '/propagation'
    | '/telemetry'
    | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faults'
    | '/graphs'
    | '/logs'
    | '/ontology'
    | '/propagation'
    | '/telemetry'
    | '/twin'
  id:
    | '__root__'
    | '/'
    | '/faults'
    | '/graphs'
    | '/logs'
    | '/ontology'
    | '/propagation'
    | '/telemetry'
    | '/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaultsRoute: typeof FaultsRoute
  GraphsRoute: typeof GraphsRoute
  LogsRoute: typeof LogsRoute
  OntologyRoute: typeof OntologyRoute
  PropagationRoute: typeof PropagationRoute
  TelemetryRoute: typeof TelemetryRoute
  TwinRoute: typeof TwinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propagation': {
      id: '/propagation'
      path: '/propagation'
      fullPath: '/propagation'
      preLoaderRoute: typeof PropagationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontology': {
      id: '/ontology'
      path: '/ontology'
      fullPath: '/ontology'
      preLoaderRoute: typeof OntologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs': {
      id: '/graphs'
      path: '/graphs'
      fullPath: '/graphs'
      preLoaderRoute: typeof GraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faults': {
      id: '/faults'
      path: '/faults'
      fullPath: '/faults'
      preLoaderRoute: typeof FaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaultsRoute: FaultsRoute,
  GraphsRoute: GraphsRoute,
  LogsRoute: LogsRoute,
  OntologyRoute: OntologyRoute,
  PropagationRoute: PropagationRoute,
  TelemetryRoute: TelemetryRoute,
  TwinRoute: TwinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
